# Generated by Django 4.2.2 on 2023-06-24 17:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("Cardiology", "Cardiology"),
                            ("Dermatology", "Dermatology"),
                            ("Endocrinology", "Endocrinology"),
                            ("Gastroenterology", "Gastroenterology"),
                            ("Neurology", "Neurology"),
                            ("Obstetrics and Gynecology", "Obstetrics and Gynecology"),
                            ("Oncology", "Oncology"),
                            ("Ophthalmology", "Ophthalmology"),
                            ("Orthopedics", "Orthopedics"),
                            ("Pediatrics", "Pediatrics"),
                            ("Psychiatry", "Psychiatry"),
                            ("Pulmonology", "Pulmonology"),
                            ("Radiology", "Radiology"),
                            ("Urology", "Urology"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prescription", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("first_name",),
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100", "100"),
                            ("200", "200"),
                            ("300", "300"),
                            ("400", "400"),
                            ("500", "500"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("address", models.CharField(max_length=256)),
                ("prescription", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("first_name",),
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptoms", models.TextField(default="", max_length=2000)),
                ("prescription", models.TextField(default="", max_length=2000)),
                ("medicine", models.CharField(max_length=256)),
                ("time_started", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("consumption", models.JSONField(default=dict)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="HealthCentre.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="HealthCentre.patient",
                    ),
                ),
            ],
        ),
    ]
