# Generated by Django 4.2.2 on 2023-06-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HealthCentre", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="patients",
            field=models.ManyToManyField(
                related_name="doctors", to="HealthCentre.patient"
            ),
        ),
    ]
