# Generated by Django 4.2.2 on 2023-06-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("HealthCentre", "0002_doctor_patients"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_patient",
                to="HealthCentre.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="patients",
            field=models.ManyToManyField(
                related_name="pateint_doctor", to="HealthCentre.patient"
            ),
        ),
    ]
