# Generated by Django 4.2.2 on 2023-06-24 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("HealthCentre", "0003_patient_doctor_alter_doctor_patients"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("expiry_date", models.DateField(default=datetime.timezone)),
                ("available", models.BooleanField(default=False)),
                ("consumption", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medicine",
        ),
        migrations.AlterField(
            model_name="prescription",
            name="consumption",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="medicine_consumption",
                to="HealthCentre.medicine",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medicine",
            field=models.ManyToManyField(
                related_name="medicine", to="HealthCentre.medicine"
            ),
        ),
    ]
