# Generated by Django 4.2.2 on 2023-06-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HealthCentre", "0004_medicine_remove_prescription_medicine_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="prescription",
        ),
    ]
