# Generated by Django 4.2.2 on 2023-06-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HealthCentre", "0005_remove_prescription_prescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="consumption",
        ),
    ]
